### ISSUE TITLE
How to create async "thunk style" action chains?

### ISSUE THREAD

**Issue by MartinMajewski** [marcelmokos/redux-create#1]
Please provide an example.

Thank you.

**Comment by marcelmokos** [comment]
I will add examples but you can create just action creators.

`
export const asyncActionType = {
  REQUEST: "REQUEST",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
};

export const createAsyncActionCreator = (...type) => ({
  request: createActionCreator(type, asyncActionType.REQUEST),
  success: createActionCreator(type, asyncActionType.SUCCESS),
  failure: createActionCreator(type, asyncActionType.FAILURE),
});
`

and then call api.

`
export const fetchProductsAction = createAsyncActionCreator(FETCH_PRODUCTS);

export const fetchProducts = () => (dispatch) => {
  dispatch(fetchProductsAction.request());

  productsApi.fetchProducts().then(
    (payload) => dispatch(fetchProductsAction.success(payload)),
    (error) => dispatch(fetchProductsAction.failure(error)),
  );
};
`

**Comment by marcelmokos** [comment]
Version 1.0.6 adds usage and async action creator.
